Repository devfolioco/react-otp-input, pull requests merged in 2020-10, with the labels that each got.

#136 updated doc
  README.md
Labels: docs

#197 remove old links from readme
  README.md
Labels: docs

#149 disable clear button when otp field is empty
  src/demo/index.jsx
Labels: demo

#120 fix#115 : Add isSecure property
  README.md
  src/demo/index.jsx
  src/lib/index.jsx
Labels: next
